[package]
name = "bourbon"
version = "0.2.0"
edition = "2021"

[features]
rocket = ["bourbon_template_macro/rocket"]

[dependencies]
bourbon_lexer = { path = "../bourbon_lexer" }
bourbon_template_macro = { version = "0.2.0", path = "../bourbon_template_macro" }
