[package]
name = "bourbon_template_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bourbon_lexer = { path = "../bourbon_lexer" }
proc-macro2 = "1.0.66"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
